### ISSUE TITLE
Scripts fails after a few hours

### ISSUE THREAD

**Issue by FritzJo** [FritzJo/volkswagen-tracker#2]
Log:
```bash
Traceback (most recent call last):
  File "./app.py", line 18, in <module>
    distanceCovered_str = getMileage(s, url)  # Pull the information from Carnet
  File "/app/vw_carnet.py", line 180, in getMileage
    json_info = json.loads(info)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by FritzJo** [comment]
hopefully fixed with https://github.com/FritzJo/volkswagen-tracker/commit/8bb498eb1993640deb75ce1a93fccdd53544c9fb

**Comment by FritzJo** [comment]
still crashes after a while...
```bash
Traceback (most recent call last):
  File "./app.py", line 20, in <module>
    add_entry(car_info_json, emanager_info_json)  # Insert the value into the database
  File "/app/database/influx.py", line 16, in add_entry
    "mileage_value": int(json_info['vehicleDetails']['distanceCovered'].replace(".", ""))
KeyError: 'vehicleDetails'
```

**Comment by FritzJo** [comment]
Seems to be fixed now. Might have been an issue with the VW servers that caused the crash.
